deploymentName ="boomi-quickstart-molecule"
projectID=""
region = ""
zone =""
boomiAuthenticationType=""
boomiUserEmailID=""
boomiPasswordORboomiAPIToken=""
boomiAccountID=""
molecule_Name=""
machineType=""
atomtype="Privatecloud or Molecule"

